#name, main, version and api are required
name: BroadcastTick
main: ExamplePlugin\MainClass
version: 1.1.0
api: 3.0.0
load: POSTWORLD
author: PocketMine Team
description: Example plugin showing the new API
